apiVersion: v1
entries:
  aerios-k8s-shim:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-03-06T15:20:58.8238871+01:00"
    description: A Helm chart for deploying an intermediate among aerios and K8s cluster
    digest: d1ebdb7474a6b576e1f34e9f9fc90561deaa2df2a6ddf7be2321f5e9df5f8b70
    name: aerios-k8s-shim
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/aerios-k8s-shim-1.0.0.tgz
    version: 1.0.0
  aeros-orchestrator-overlay:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-03-06T15:20:58.8249227+01:00"
    description: A Helm chart for Kubernetes
    digest: 9ab78ef17d5d2b0dcfa2abff285a8735c0ae12bb845d2dfb6a6df2e288972483
    name: aeros-orchestrator-overlay
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/aeros-orchestrator-overlay-2.0.0.tgz
    version: 2.0.0
  api-gateway:
  - apiVersion: v2
    appVersion: 1.6.0
    created: "2026-03-06T15:20:58.8267535+01:00"
    description: API Gateway for the aeriOS domains
    digest: a4b0ad69f01eecb035bee533d117fd38229f3fa39016f57db5ff35e024e76ec7
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - API
    - gateway
    - domain
    - KrakenD
    name: api-gateway
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/api-gateway-1.6.0.tgz
    version: 1.6.0
  benchmarking-tool:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-03-06T15:20:58.8277586+01:00"
    description: A Helm chart for Kubernetes
    digest: 9f6f1c70588d38c477c24261a69907b14ccec9aadfe467e0a027d776df7bc0b8
    name: benchmarking-tool
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/benchmarking-tool-1.0.0.tgz
    version: 1.0.0
  entrypoint-balancer:
  - apiVersion: v2
    appVersion: 1.3.0
    created: "2026-03-06T15:20:58.8277586+01:00"
    description: Eclipse aeriOS Entrypoint Balancer
    digest: 24f6e94f395a3fe13d2daa0592dd8c788465aa90384a02639cf25aaec14025f6
    name: entrypoint-balancer
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/entrypoint-balancer-1.3.0.tgz
    version: 1.3.0
  federator:
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2026-03-06T15:20:58.8287218+01:00"
    description: aeriOS Federator
    digest: dfb49953fec551ae1dd631cfb96e1ce11329e416c90eaf70e78b2c27b2c6d4ab
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - federator
    - domain
    - domain-federation
    - NGSI-LD
    - Orion-LD
    - ContextSourceRegistration
    name: federator
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/federator-1.1.0.tgz
    version: 1.1.0
  hlo-allocator:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-03-06T15:20:58.8297218+01:00"
    description: A Helm chart for Kubernetes
    digest: b9d809c3fdf03b6baa7663f33c2f212cc99bd0725521c22b9cfa96aeca0dc8fe
    name: hlo-allocator
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/hlo-allocator-3.0.0.tgz
    version: 3.0.0
  hlo-data-aggregator:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-03-06T15:20:58.8307555+01:00"
    description: A Helm chart for Kubernetes
    digest: df2ecb788f77442c66712489ab57bd9c7b10471bed5cb2daa9e60933749414ba
    name: hlo-data-aggregator
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/hlo-data-aggregator-3.0.0.tgz
    version: 3.0.0
  hlo-deployment-engine:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-03-06T15:20:58.8307555+01:00"
    description: A Helm chart for Kubernetes
    digest: e6e6c586c0067c931898eed90a98221c6bdd9203455ddf21cc8c187db9b1580f
    name: hlo-deployment-engine
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/hlo-deployment-engine-3.0.0.tgz
    version: 3.0.0
  hlo-deployments:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-03-06T15:20:58.8337218+01:00"
    dependencies:
    - condition: local-fe-engine.enabled
      name: local-fe-engine
      repository: file://charts/local-fe-engine
      version: 3.0.0
    - condition: data-aggregator.enabled
      name: data-aggregator
      repository: file://charts/data-aggregator
      version: 3.0.0
    - condition: hlo-allocator.enabled
      name: hlo-allocator
      repository: file://charts/hlo-allocator
      version: 3.0.0
    - condition: local-allocation-manager.enabled
      name: local-allocation-manager
      repository: file://charts/local-allocation-manager
      version: 3.0.0
    description: A Helm chart for Kubernetes installing HLO-frontend, hlo-allocator,
      hlo-allocation-manager, and hlo-data-aggregator
    digest: 2cedbe5cdc428cc107f73fd6fa07b9c7d267731e998ea6ce5de3d04862c056e0
    name: hlo-deployments
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/hlo-deployments-1.0.0.tgz
    version: 1.0.0
  hlo-fe-engine:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-03-06T15:20:58.8347218+01:00"
    description: A Helm chart for Kubernetes
    digest: d8a27ab687eed4a41121fd321d7e31dbd3e7b47214dcfcdf1b9a19a7838e4ed1
    name: hlo-fe-engine
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/hlo-fe-engine-3.0.0.tgz
    version: 3.0.0
  idm:
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2026-03-06T15:20:58.8357214+01:00"
    description: Helm chart for the aerios Identity Manager based on Keycloak
    digest: 6c121388269119028260b298f856578115c5cd2a759a02998f960d246801c4d3
    keywords:
    - ravaga-helm-chart-generator
    - aerios
    - keycloak
    - oauth2.0
    - cybersecurity
    - idm
    name: idm
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/idm-1.1.0.tgz
    version: 1.1.0
  iota:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2026-03-06T15:20:58.836721+01:00"
    description: IOTA tangle Helm chart
    digest: 84ca51ca01f590eedbedddc3ee11f756140d6ee493c471c1c10f00d995e2b9e2
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - IOTA
    - iota-tangle
    - trustworthiness
    name: iota
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/iota-1.0.2.tgz
    version: 1.0.2
  llo-api:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2026-03-06T15:20:58.8377208+01:00"
    description: A Helm chart for the aeriOS LLO API
    digest: 37dfac34b45f312bfd7d67daff5f50ae706e25a63f6073bac8e4ce917325dd7c
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - LLO
    - API
    - orchestration
    name: llo-api
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/llo-api-1.0.0.tgz
    version: 1.0.0
  llo-docker-operator:
  - apiVersion: v2
    appVersion: 1.1.2
    created: "2026-03-06T15:20:58.8387209+01:00"
    description: A Helm chart for the K8s Operator of the LLO Docker
    digest: dfee4ac5c1c87f20231441ba9e8410854dac1e9dd363889dfbe7bf9920b58ab3
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - LLO
    - Docker
    - orchestration
    - operator
    - nats
    name: llo-docker-operator
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/llo-docker-operator-1.0.0.tgz
    version: 1.0.0
  llo-k8s:
  - apiVersion: v2
    appVersion: 1.4.1
    created: "2026-03-06T15:20:58.839721+01:00"
    description: A Helm chart for the Operator of the Eclipse aeriOS LLO K8s
    digest: b421fac15f07181179f8e1b8fdffcbb28eb73bb7ef5762c8d9470b9dba7fdf21
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - LLO
    - K8s
    - orchestration
    - operator
    name: llo-k8s
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/llo-k8s-1.1.0.tgz
    version: 1.1.0
  llo-nats:
  - apiVersion: v2
    appVersion: 2.11.4
    created: "2026-03-06T15:20:58.8407216+01:00"
    description: A Helm chart for the NATS broker used by the aeriOS LLOs
    digest: dcdf02ac65a0925aae44c2289e7739134d2ccc2ca57007548cacc1868e85e39c
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - LLO
    - no-k8s
    - operator
    - nats
    - broker
    - asynchronous
    - CNCF
    name: llo-nats
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/llo-nats-1.0.0.tgz
    version: 1.0.0
  management-portal:
  - apiVersion: v2
    appVersion: 1.2.2
    created: "2026-03-06T15:20:58.8417214+01:00"
    description: aeriOS Management Portal
    digest: 971dc294885154e1e90fbec338fd56e966a97461e908593e29fe2b6e0613d94b
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - management
    - framework
    - portal
    - dashboard
    - meta-os
    name: management-portal
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/management-portal-1.1.0.tgz
    version: 1.1.0
  mintaka:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-03-06T15:20:58.8427225+01:00"
    description: A Helm chart for FIWARE Mintaka
    digest: 2da3d2679e8b5957182b495b3bb66b672d14d2ffa63545171c02916a1d1e92a5
    keywords:
    - ravaga-helm-chart-generator
    - fiware
    - mintaka
    - aeriOS
    - ngsi-ld
    - persistence
    - historical
    - data
    name: mintaka
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/mintaka-1.0.0.tgz
    version: 1.0.0
  openfaas2:
  - apiVersion: v2
    created: "2026-03-06T15:20:58.8447216+01:00"
    description: OpenFaaS - Serverless Functions Made Simple
    digest: 931e32604abd6cbb6830af22b01b9124081207942adc51af132255abb1681eae
    keywords:
    - serverless
    - functions
    - platform
    - faas
    maintainers:
    - email: alex@openfaas.com
      name: alexellis
    - email: han@openfaas.com
      name: welteki
    - email: roesler.lucas@gmail.com
      name: lucasroesler
    name: openfaas2
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/openfaas2-12.0.5.tgz
    version: 12.0.5
  openldap-stack-ha:
  - apiVersion: v2
    appVersion: 2.6.4
    created: "2026-03-06T15:20:58.8487208+01:00"
    dependencies:
    - condition: ltb-passwd.enabled
      name: ltb-passwd
      repository: ""
      version: 0.1.x
    - condition: phpldapadmin.enabled
      name: phpldapadmin
      repository: ""
      version: 0.1.x
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Community developed LDAP software
    digest: d85111efbc382fe3e1440ef4a5b9da165f5178696657cc899ba4dc16e7b16054
    home: https://www.openldap.org
    icon: https://raw.githubusercontent.com/jp-gouin/helm-openldap/master/logo.png
    keywords:
    - ldap
    - openldap
    - iam-stack
    - high availability
    maintainers:
    - email: jp-gouin@hotmail.fr
      name: Jean-Philippe Gouin
    name: openldap-stack-ha
    sources:
    - https://github.com/jp-gouin/helm-openldap
    urls:
    - https://eclipse-aerios.github.io/resources/charts/openldap-stack-ha-4.1.2.tgz
    version: 4.1.2
  orion-ld:
  - apiVersion: v2
    appVersion: 1.10.0
    created: "2026-03-06T15:20:58.8497213+01:00"
    description: A Helm chart for FIWARE Orion-LD context broker. The default values
      have been adapted to the needs of the aeriOS project.
    digest: 0da9cd1ef3647b40d246759ef29662ccdc44f3ecccfd8a3aeda3738b908051e8
    keywords:
    - fiware
    - orion-ld
    - orion
    - aeriOS
    - context-broker
    - ngsi-ld
    kubeVersion: '>= 1.23-0'
    name: orion-ld
    sources:
    - https://github.com/FIWARE/context.Orion-LD
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/orion-ld-1.0.0.tgz
    version: 1.0.0
  redpanda:
  - annotations:
      artifacthub.io/images: |
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:v23.3.1
        - name: busybox
          image: busybox:latest
        - name: mintel/docker-alpine-bash-curl-jq
          image: mintel/docker-alpine-bash-curl-jq:latest
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Documentation
          url: https://docs.redpanda.com
        - name: "Helm (>= 3.8.0)"
          url: https://helm.sh/docs/intro/install/
    apiVersion: v2
    appVersion: v23.3.1
    created: "2026-03-06T15:20:58.8557305+01:00"
    dependencies:
    - condition: console.enabled
      name: console
      repository: https://charts.redpanda.com
      version: '>=0.5 <1.0'
    - condition: connectors.enabled
      name: connectors
      repository: https://charts.redpanda.com
      version: '>=0.1.2 <1.0'
    description: Redpanda is the real-time engine for modern apps.
    digest: 50b40f4204ec612e8de2cd1f8cf59f4224a3512ddd9cbe31b1ebd291e18da72d
    icon: https://images.ctfassets.net/paqvtpyf8rwu/3cYHw5UzhXCbKuR24GDFGO/73fb682e6157d11c10d5b2b5da1d5af0/skate-stand-panda.svg
    kubeVersion: ^1.21.0-0
    maintainers:
    - name: redpanda-data
      url: https://github.com/orgs/redpanda-data/people
    - name: aerios-team
      url: https://github.com/orgs/eclipse-aerios/people
    name: redpanda
    sources:
    - https://github.com/redpanda-data/helm-charts
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/redpanda-5.7.8.tgz
    version: 5.7.8
  self-awareness:
  - apiVersion: v2
    appVersion: 1.4.4
    created: "2026-03-06T15:20:58.8568475+01:00"
    description: Self-awareness module of the aeriOS Self-* components
    digest: 4b032480903a3417c2d7c049ee9c3b649a02061c0e5e9332d858ac64220249ca
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - self-*
    - metrics
    name: self-awareness
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/self-awareness-1.4.4.tgz
    version: 1.4.4
  self-orchestrator:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2026-03-06T15:20:58.8573727+01:00"
    description: Self-orchestrator module of the Self-* modules of aeriOS
    digest: b311e848f89df9a007c5116ca6392716478e2ec66fbb420aad39dc4a80d856ef
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - self-*
    name: self-orchestrator
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/self-orchestrator-1.2.0.tgz
    version: 1.2.0
  trustmanager:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-03-06T15:20:58.8578862+01:00"
    description: 'Helm chart for deploying the Trust Manager system, which integrates
      Orion Broker, self-awareness,  self-security, and self-healing mechanisms to
      calculate trust scores for Infrastructure Elements (IEs)  within a domain. '
    digest: 068aa4d8a78904a8ab3862c6e4a76f20b78ca7a442a9ab4c9886f0b3bc4db278
    keywords:
    - aeriOS
    - trustworthiness
    - trust-score
    - meta-os
    name: trustmanager
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/trustmanager-1.0.0.tgz
    version: 1.0.0
generated: "2026-03-06T15:20:58.8187951+01:00"
