apiVersion: v1
entries:
  aerios-k8s-shim:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-11-24T13:19:15.853197+01:00"
    description: A Helm chart for deploying an intermediate among aerios and K8s cluster
    digest: be15dde9ddd150e559fd1f48b61e060e1643178c4185e1fff7e748ed5f0ebeb7
    name: aerios-k8s-shim
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/aerios-k8s-shim-1.0.0.tgz
    version: 1.0.0
  federator:
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2025-11-24T13:19:15.8537469+01:00"
    description: aeriOS Federator
    digest: 43bb0150a5b83de99adfd3e96b4911aef3f63f739a2a6a6a39d6b011f6aada6b
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - federator
    - domain
    - domain-federation
    - NGSI-LD
    - Orion-LD
    - ContextSourceRegistration
    name: federator
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/federator-1.1.0.tgz
    version: 1.1.0
  mintaka:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-24T13:19:15.8542958+01:00"
    description: A Helm chart for FIWARE Mintaka
    digest: 2da3d2679e8b5957182b495b3bb66b672d14d2ffa63545171c02916a1d1e92a5
    keywords:
    - ravaga-helm-chart-generator
    - fiware
    - mintaka
    - aeriOS
    - ngsi-ld
    - persistence
    - historical
    - data
    name: mintaka
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/mintaka-1.0.0.tgz
    version: 1.0.0
  orion-ld:
  - apiVersion: v2
    appVersion: 1.10.0
    created: "2025-11-24T13:19:15.8553957+01:00"
    description: A Helm chart for FIWARE Orion-LD context broker. The default values
      have been adapted to the needs of the aeriOS project.
    digest: 0da9cd1ef3647b40d246759ef29662ccdc44f3ecccfd8a3aeda3738b908051e8
    keywords:
    - fiware
    - orion-ld
    - orion
    - aeriOS
    - context-broker
    - ngsi-ld
    kubeVersion: '>= 1.23-0'
    name: orion-ld
    sources:
    - https://github.com/FIWARE/context.Orion-LD
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/orion-ld-1.0.0.tgz
    version: 1.0.0
generated: "2025-11-24T13:19:15.8526466+01:00"
