apiVersion: v1
entries:
  aerios-k8s-shim:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-04T16:23:22.104958909+02:00"
    description: A Helm chart for deploying an intermediate among aerios and K8s cluster
    digest: be15dde9ddd150e559fd1f48b61e060e1643178c4185e1fff7e748ed5f0ebeb7
    name: aerios-k8s-shim
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/aerios-k8s-shim-1.0.0.tgz
    version: 1.0.0
  aeros-orchestrator-overlay:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-04T16:23:22.105254427+02:00"
    description: A Helm chart for Kubernetes
    digest: 9ab78ef17d5d2b0dcfa2abff285a8735c0ae12bb845d2dfb6a6df2e288972483
    name: aeros-orchestrator-overlay
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/aeros-orchestrator-overlay-2.0.0.tgz
    version: 2.0.0
  federator:
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2025-12-04T16:23:22.105531439+02:00"
    description: aeriOS Federator
    digest: dfb49953fec551ae1dd631cfb96e1ce11329e416c90eaf70e78b2c27b2c6d4ab
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - federator
    - domain
    - domain-federation
    - NGSI-LD
    - Orion-LD
    - ContextSourceRegistration
    name: federator
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/federator-1.1.0.tgz
    version: 1.1.0
  idm:
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2025-12-04T16:23:22.105958521+02:00"
    description: Helm chart for the aerios Identity Manager based on Keycloak
    digest: 6c121388269119028260b298f856578115c5cd2a759a02998f960d246801c4d3
    keywords:
    - ravaga-helm-chart-generator
    - aerios
    - keycloak
    - oauth2.0
    - cybersecurity
    - idm
    name: idm
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/idm-1.1.0.tgz
    version: 1.1.0
  iota:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2025-12-04T16:23:22.106650606+02:00"
    description: iota helm chart
    digest: 43e71aa7ce0fc546b455897f937ecad557e8b1ae7016817db49e850eebffb522
    keywords:
    - ravaga-helm-chart-generator
    name: iota
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/iota-1.0.2.tgz
    version: 1.0.2
  llo-api:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2025-12-04T16:23:22.106913427+02:00"
    description: A Helm chart for the aeriOS LLO API
    digest: 37dfac34b45f312bfd7d67daff5f50ae706e25a63f6073bac8e4ce917325dd7c
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - LLO
    - API
    - orchestration
    name: llo-api
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/llo-api-1.0.0.tgz
    version: 1.0.0
  llo-nats:
  - apiVersion: v2
    appVersion: 2.11.4
    created: "2025-12-04T16:23:22.10724296+02:00"
    description: A Helm chart for the NATS broker used by the aeriOS LLOs
    digest: dcdf02ac65a0925aae44c2289e7739134d2ccc2ca57007548cacc1868e85e39c
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - LLO
    - no-k8s
    - operator
    - nats
    - broker
    - asynchronous
    - CNCF
    name: llo-nats
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/llo-nats-1.0.0.tgz
    version: 1.0.0
  mintaka:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-12-04T16:23:22.107608788+02:00"
    description: A Helm chart for FIWARE Mintaka
    digest: 2da3d2679e8b5957182b495b3bb66b672d14d2ffa63545171c02916a1d1e92a5
    keywords:
    - ravaga-helm-chart-generator
    - fiware
    - mintaka
    - aeriOS
    - ngsi-ld
    - persistence
    - historical
    - data
    name: mintaka
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/mintaka-1.0.0.tgz
    version: 1.0.0
  openldap-stack-ha:
  - apiVersion: v2
    appVersion: 2.6.4
    created: "2025-12-04T16:23:22.112461604+02:00"
    dependencies:
    - condition: ltb-passwd.enabled
      name: ltb-passwd
      repository: ""
      version: 0.1.x
    - condition: phpldapadmin.enabled
      name: phpldapadmin
      repository: ""
      version: 0.1.x
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Community developed LDAP software
    digest: d85111efbc382fe3e1440ef4a5b9da165f5178696657cc899ba4dc16e7b16054
    home: https://www.openldap.org
    icon: https://raw.githubusercontent.com/jp-gouin/helm-openldap/master/logo.png
    keywords:
    - ldap
    - openldap
    - iam-stack
    - high availability
    maintainers:
    - email: jp-gouin@hotmail.fr
      name: Jean-Philippe Gouin
    name: openldap-stack-ha
    sources:
    - https://github.com/jp-gouin/helm-openldap
    urls:
    - https://eclipse-aerios.github.io/resources/charts/openldap-stack-ha-4.1.2.tgz
    version: 4.1.2
  orion-ld:
  - apiVersion: v2
    appVersion: 1.10.0
    created: "2025-12-04T16:23:22.113112915+02:00"
    description: A Helm chart for FIWARE Orion-LD context broker. The default values
      have been adapted to the needs of the aeriOS project.
    digest: 0da9cd1ef3647b40d246759ef29662ccdc44f3ecccfd8a3aeda3738b908051e8
    keywords:
    - fiware
    - orion-ld
    - orion
    - aeriOS
    - context-broker
    - ngsi-ld
    kubeVersion: '>= 1.23-0'
    name: orion-ld
    sources:
    - https://github.com/FIWARE/context.Orion-LD
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/orion-ld-1.0.0.tgz
    version: 1.0.0
  redpanda:
  - annotations:
      artifacthub.io/images: |
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:v23.3.1
        - name: busybox
          image: busybox:latest
        - name: mintel/docker-alpine-bash-curl-jq
          image: mintel/docker-alpine-bash-curl-jq:latest
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Documentation
          url: https://docs.redpanda.com
        - name: "Helm (>= 3.8.0)"
          url: https://helm.sh/docs/intro/install/
    apiVersion: v2
    appVersion: v23.3.1
    created: "2025-12-04T16:23:22.117617866+02:00"
    dependencies:
    - condition: console.enabled
      name: console
      repository: https://charts.redpanda.com
      version: '>=0.5 <1.0'
    - condition: connectors.enabled
      name: connectors
      repository: https://charts.redpanda.com
      version: '>=0.1.2 <1.0'
    description: Redpanda is the real-time engine for modern apps.
    digest: 50b40f4204ec612e8de2cd1f8cf59f4224a3512ddd9cbe31b1ebd291e18da72d
    icon: https://images.ctfassets.net/paqvtpyf8rwu/3cYHw5UzhXCbKuR24GDFGO/73fb682e6157d11c10d5b2b5da1d5af0/skate-stand-panda.svg
    kubeVersion: ^1.21.0-0
    maintainers:
    - name: redpanda-data
      url: https://github.com/orgs/redpanda-data/people
    - name: aerios-team
      url: https://github.com/orgs/eclipse-aerios/people
    name: redpanda
    sources:
    - https://github.com/redpanda-data/helm-charts
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/redpanda-5.7.8.tgz
    version: 5.7.8
  self-awareness:
  - apiVersion: v2
    appVersion: 1.4.4
    created: "2025-12-04T16:23:22.118204693+02:00"
    description: Self-awareness module of the aeriOS Self-* components
    digest: 4b032480903a3417c2d7c049ee9c3b649a02061c0e5e9332d858ac64220249ca
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - self-*
    - metrics
    name: self-awareness
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/self-awareness-1.4.4.tgz
    version: 1.4.4
  self-orchestrator:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2025-12-04T16:23:22.118358622+02:00"
    description: Self-orchestrator module of the Self-* modules of aeriOS
    digest: b311e848f89df9a007c5116ca6392716478e2ec66fbb420aad39dc4a80d856ef
    keywords:
    - ravaga-helm-chart-generator
    - aeriOS
    - self-*
    name: self-orchestrator
    type: application
    urls:
    - https://eclipse-aerios.github.io/resources/charts/self-orchestrator-1.2.0.tgz
    version: 1.2.0
generated: "2025-12-04T16:23:22.103388289+02:00"
